- name: "student"
  hosts: master 
  become_method: sudo
  become_user: root
  become: no
  vars:
    ansible_python_interpreter: python3
    ansible_become_pass: root
    ansible_pkg_mgr: apt
    eclipse_base_dir: "/home/vagrant/ide/eclipse" 
  tasks:
    - name: Include task list 
      include_tasks: "ansible/tasks/main.yml"
      
    - name: change shell to zsh
      expect:
        command: "chsh -s /usr/bin/zsh"
        responses:
          (?i)password: "vagrant"

    - name: change keyboard to spanish
      expect:
        command: "localectl set-keymap es"
        responses:
          (?i)password: "vagrant"
        
    
    - name: allow current user to manage docker
      file:
        path: /var/run/docker.sock
        owner: vagrant
        group: vagrant
      become: true

 
