- name: Check if oh-my-zsh previous installed
  stat: 
    path: ~/.oh-my-zsh
  register: previous_zsh_instalation
  become: false

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  register: cloning
  when: previous_zsh_instalation
  become: false

- name: zsh-history-substring-search
  git:
    repo: https://github.com/zsh-users/zsh-history-substring-search.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-history-substring-search

- name: zsh-vi-mode
  git:
    repo: https://github.com/jeffreytse/zsh-vi-mode.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-vi-mode

- name: zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Installing git configfiles
  git:
    repo: https://github.com/Programador753/.DotFiles.git
    dest: ~/.DotFiles
  ignore_errors: yes

- name: zshrc symlink
  file: 
    path: ~/.zshrc 
    src: ~/.DotFiles/.zshrc  
    state: link 
    force: yes

- name: mycli config folder
  file: 
    path: ~/.config/mycli/  
    state: directory 
    mode: '666'
  ignore_errors: yes

- name: pgcli config folder
  file: 
    path: ~/.config/pgcli/  
    state: directory 
    mode: '666'
  ignore_errors: yes

- name: litecli config folder
  file: 
    path: ~/.config/litecli/  
    state: directory 
    mode: '666'
  ignore_errors: yes

- name: mssql config folder
  file: 
    path: ~/.config/mssql/  
    state: directory 
    mode: '666'
  ignore_errors: yes

- name: iredis config folder
  file: 
    path: ~/.config/iredis/  
    state: directory 
    mode: '666'
  ignore_errors: yes

- name: mycli symlink
  file: 
    path: ~/.myclirc 
    src: ~/.config/mycli/.myclirc  
    state: link 
    force: yes

- name: pgcli symlink
  file: 
    path: ~/.DotFiles/pgcli/config
    src: ~/.config/pgcli/config
    state: link 
    force: yes

- name: litecli symlink
  file: 
    path: ~/.DotFiles/litecli/config 
    src:   ~/.config/litecli/config
    state: link 
    force: yes

- name: mssql symlink
  file: 
    path: ~/.DotFiles/mssqlcli/config
    src:  ~/.config/mssqlcli/config 
    state: link 
    force: yes

- name: iredis symlink
  file: 
    path: ~/.DotFiles/iredis/.iredisrc 
    src:  ~/.iredisrc 
    state: link 
    force: yes

- name: Installing zsh completions
  git:
    repo: https://github.com/zsh-users/zsh-completions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-completions

- name: Installing zsh-history-substring
  git:
    repo: https://github.com/zsh-users/zsh-history-substring-search.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-history-substring-search


- name: Installing-pure-prompt
  git:
    repo: https://github.com/sindresorhus/pure.git
    dest: ~/.zsh/pure
    version: main

- name: change shell to zsh
  shell: "chsh -s /usr/bin/zsh"
  become: true
